### ISSUE TITLE
🐛Bug: Select inside dialog causes dialog to close when an item is selected

### ISSUE THREAD

**Issue by buhodev** [melt-ui/melt-ui#451]
**Describe the bug**

Selecting an item from a Select component inside a dialog causes the dialog to close (I suppose due to the way the outsideClick logic is handled). This also happens with any element outside the dialog (e.g. an always on display bottom navbar with a hamburguer button that opens the dialog (and changes to a X button to close it when the dialog is open).

**To Reproduce**
1. Go to https://www.sveltelab.dev/2kezbln53cyozjz
2. Click on 'Open Dialog' button
3. Select a flavor from the Select inside the Dialog
4. See error (dialog closes)

**Expected behavior**
Dialog _shouldn't_ close when selecting a item from a Select component inside the dialog

**Comment by TGlide** [comment]
Thanks for raising this issue! @buhodev since there are two bugs, please create a separate issue for the second bug 😄

**Comment by buhodev** [comment]
> Thanks for raising this issue! @buhodev since there are two bugs, please create a separate issue for the second bug 😄

Done https://github.com/melt-ui/melt-ui/issues/452 :wink:

**Comment by softwarecurator** [comment]
https://stackblitz.com/edit/kit-ts-tw-melt-mclbpf?file=package.json seems to be still an issue on `0.39.0`

**Comment by TGlide** [comment]
> https://stackblitz.com/edit/kit-ts-tw-melt-mclbpf?file=package.json seems to be still an issue on `0.39.0`

0.39.0 does not try to address this issue, this is expected.

**Comment by huntabyte** [comment]
The same happens inside of a `Popover`. It appears the select isn't respecting any portal parent's and is always portalling to the body, even when `portal: null`

**Comment by thomasefbland** [comment]
> The same happens inside of a `Popover`. It appears the select isn't respecting any portal parent's and is always portalling to the body, even when `portal: null`

Interestingly though, when you "fix" this by providing portal: selector, to the dialog portal element, it now nests inside correctly, yet the closing on select issue persists
